# Generated by Django 4.2.5 on 2024-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
